# Generated by Django 5.1.2 on 2024-10-29 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_constructorainmobiliaria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorainmobiliaria',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='constructora_inmobiliaria', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
