# Generated by Django 5.1.2 on 2024-10-29 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_constructorainmobiliaria_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructorainmobiliaria',
            name='user',
        ),
        migrations.CreateModel(
            name='BuilderCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incorporation_time', models.PositiveIntegerField(help_text='Años de constitución')),
                ('legal_representative', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder_company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_advisors/')),
                ('biography', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
                ('num_sales', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_advisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AsesorComercial',
        ),
        migrations.DeleteModel(
            name='ConstructoraInmobiliaria',
        ),
    ]
