# Generated by Django 5.1.2 on 2024-11-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_constructorainmobiliaria_user_buildercompany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialadvisor',
            name='photo',
        ),
    ]
